<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWOJUL4X\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWOJUL4X/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWOJUL4X.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWOJUL4X\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWOJUL4X\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WOJUL4X',
    'container.build_id' => 'f74fc58e',
    'container.build_time' => 1558379025,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWOJUL4X');
